language: python
cache: pip

python:
    - "3.7"

install:
  - pip install -r scrape_data_requirements.txt

env:
  global:
  - ORG="python-sprints"
  - EMAIL="joytolia@hotmail.com"
  - REPO="pyntxos-dashboard"
  - COPY_DIR_FILE="./data ./utils environment.yml dashboard.ipynb"
  - GH_REPO="github.com/${ORG}/${REPO}.git"

script:
  - python -c 'import utils.data; utils.data.dump(utils.data.scrape())'
  - git clone git://${GH_REPO}
  - cd ${REPO}
  - rm -rf ${COPY_DIR_FILE}
  - cd ..
  - mv ${COPY_DIR_FILE} ${REPO}
  - cd ${REPO}
  - git remote
  - git config user.email ${EMAIL}
  - git config user.name ${USER}
  - git add ${COPY_DIR_FILE}
  - git diff --quiet && git diff --staged --quiet || git commit -m "update data and dashboard"
  - git push "https://${GITHUB_API_KEY}@${GH_REPO}" master
